- hosts: all
  become: yes
  become_method: sudo
  tasks:
  - name: Update and upgrade packages
    apt:
      name: '*'
      state: latest
      update_cache: yes
      only_upgrade: yes
  - name: Install packages for PHP 5.6
    apt:
      name: ['apt-transport-https', 'lsb-release', 'ca-certificates']
  - name: Adding GPG key
    apt_key:
     url: https://packages.sury.org/php/apt.gpg
     state: present
  - name: Adding repository
    apt_repository:
     repo: deb https://packages.sury.org/php stretch main
     state: present
  - name: Installing PHP 5.6
    apt:
     name: ['php5.6', 'php5.6-fpm', 'libapache2-mod-php5.6']
